### PR TITLE
Remove Guzzle library

### LINKED ISSUE #34: Make Guzzle package optional
Currently `guzzlehttp/guzzle` is required only when `OpenExchangeRatesDriver` is used. It would be nice to eliminate it from required packages. We could add it to suggestions or replace it with plain PHP (why to require 3rd party library for single __optional__ request?).

### PR DESCRIPTION
**Pull request by trandangtri**
Close #34

### CODE REVIEW

**Comment by mvar** [comment]
@trandangtri you cannot call real 3rd party service in your tests. You should mock it somehow.

**Comment by saimaz** [comment]
@trandangtri  the issue is about to make it OPTIONAL not to REMOVE.

**Comment by saimaz** [comment]
`Guzzle` has a http mock. You can use it to simulate actual request to openexchange service by pretending that it works.

**Comment by trandangtri** [comment]
The OpenExchangeDriver just calls a normal json request to a 3rd party service, I dont think we need to use Guzzle. That's why I do suggest replace it by a curl request.

**Comment by saimaz** [comment]
Disagree. Guzzle is perfect object oriented HTTP client, which is has tests, is testable and well maintained. OpenExchange rate is one of many 3rd party providers for currency. Normally when somebody will use this bundle they will need a HTTP connection anyway. So to give an advice for user to install Guzzle is nice to have IMO.

**Comment by saimaz** [comment]
The only way to test a native curl function would be to use aspect oriented mocking library which would be hardcore style :smile:

**Comment by murnieza** [comment]
Another advantage of using Guzzle is easily controllable logging. 

I also think that it should not be replaced with plain curl.

**Comment by trandangtri** [comment]
I misunderstood this issue. I think I should close this and will back with a new PR

**Pull request closed without merging**
