### PR TITLE
Make Guzzle package optional

### LINKED ISSUE #34: Make Guzzle package optional
Currently `guzzlehttp/guzzle` is required only when `OpenExchangeRatesDriver` is used. It would be nice to eliminate it from required packages. We could add it to suggestions or replace it with plain PHP (why to require 3rd party library for single __optional__ request?).

### PR DESCRIPTION
**Pull request by trandangtri**
Closes #34.

### CODE REVIEW

**Comment by trandangtri** [comment]
Please merge https://github.com/ongr-io/CurrencyExchangeBundle/pull/41 first.

**Comment by saimaz** [comment]
I see there is still guzzle `~5.0`, the new major version is `6`. Excpet the difference that 6'th version supports PSR-7 are there any other differences or BC brakes? I think we should suggest to use latest major version.

**Comment by trandangtri** [comment]
Some updates from v5 to v6, we could take a look at here
https://github.com/guzzle/guzzle/blob/master/UPGRADING.md

As I knew, we are using `Guzzle` in CurrencyExchangeBundle only. And all tests passed after I'd updated the Guzzle lib. So what do you think if I upgrade it to the latest version? Furthermore, this is just an optional library.

**Comment by saimaz** [comment]
Yes you should update to Guzzle 6.0

**Comment by trandangtri** [comment]
I did, thanks @saimaz.

**Comment by trandangtri** [comment]
How's about this, guys?

**Comment by saimaz** [comment]
Can you rebase it to one commit?

**Comment by trandangtri** [comment]
Yes, I did

**Pull request merged**
